// DateIdeaDetailsStyles.js - refactored for dark mode compatibility
import { StyleSheet } from 'react-native';

export const createDateIdeaDetailsStyles = (theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.background,
  },
  fallbackContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    backgroundColor: theme.background,
    marginTop: 50,
  },
  fallbackText: {
    fontSize: 16,
    color: theme.text,
    textAlign: 'center',
    marginBottom: 20,
  },
  fallbackButton: {
    backgroundColor: theme.primary,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
  },
  fallbackButtonText: {
    color: theme.card,
    fontWeight: 'bold',
  },
  image: {
    width: '100%',
    height: 250,
    marginTop: 30,
  },
  detailscontent: {
    padding: 20,
    marginBottom: 20,
  },
  detailstitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: theme.text,
    marginBottom: 10,
  },
  detailsdescription: {
    fontSize: 16,
    color: theme.text,
    marginBottom: 10,
    lineHeight: 22,
  },
  detailsprice: {
    fontSize: 16,
    fontWeight: 'bold',
    color: theme.primary,
    marginBottom: 10,
  },
  detailscheck: {
    fontSize: 16,
    fontWeight: 'bold',
    color: theme.text,
    marginBottom: 15,
  },
  detailsButtonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    gap: 10,
  },
  detailswebsiteButton: {
    backgroundColor: theme.primary,
    paddingVertical: 12,
    borderRadius: 8,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    marginRight: 5,
  },
  detailsmapButton: {
    backgroundColor: theme.success,
    paddingVertical: 12,
    borderRadius: 8,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    marginLeft: 5,
  },
  detailsmapFullWidthButton: {
    backgroundColor: theme.success,
    paddingVertical: 12,
    borderRadius: 8,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
  },
    detailswebsiteFullWidthButton: {
    backgroundColor: theme.primary,
    paddingVertical: 12,
    borderRadius: 8,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  detailswebsiteButtonText: {
    color: 'white',
    fontWeight: 'bold',
    marginLeft: 8,
  },
  detailsshareButton: {
    backgroundColor: theme.border,
    paddingVertical: 12,
    borderRadius: 8,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    marginRight: 5,
  },
  detailssaveButtonInline: {
    backgroundColor: theme.border,
    paddingVertical: 12,
    borderRadius: 8,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    marginLeft: 5,
  },
  detailsbookButton: {
    backgroundColor: theme.success,
    paddingVertical: 12,
    borderRadius: 8,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    marginRight: 5,
  },
  detailsitineraryButton: {
    backgroundColor: theme.primary,
    paddingVertical: 12,
    borderRadius: 8,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    marginLeft: 5,
  },
  ///
    detailsitineraryFullWidthButton: {
    backgroundColor: theme.primary,
    paddingVertical: 12,
    borderRadius: 8,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  detailsactionText: {
    marginLeft: 8,
    fontWeight: 'bold',
    color: theme.text,
  },
  detailsbookText: {
    marginLeft: 8,
    fontWeight: 'bold',
    color: 'white',
  },
  detailsitineraryButtonText: {
    marginLeft: 8,
    fontWeight: 'bold',
    color: 'white',
  },
    itineraryBadge: {
    position: 'absolute',
    top: 20,
    right: 15,
    backgroundColor: theme.card,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
    zIndex: 10,
    elevation: 5,
  },

  itineraryBadgeText: {
    color: 'black',
    fontWeight: 'bold',
    fontSize: 13,
},
});
