// HomeScreenStyles.js - Fully consolidated and updated for dark mode support
import { StyleSheet, Dimensions } from 'react-native';

const SCREEN_WIDTH = Dimensions.get('window').width;
const CARD_WIDTH = Math.round(SCREEN_WIDTH * 0.90); // Synced with SwipeDeck

export const createHomeScreenStyles = (theme) => StyleSheet.create({
  blurOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#000',
    opacity: 0.75,
    borderRadius: 16,
    zIndex: 2,
  },
  madeWithRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 5,
  },
  madeWithText: {
    fontSize: 14,
    color: theme.textSecondary,
  },
  heartIcon: {
    marginLeft: 4,
    color: theme.textSecondary,
  },

  section: {
    marginTop: 0,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.text,
  },
  container: {
    flex: 1,
    backgroundColor: theme.background,
  },
  headerWrapper: {
    paddingTop: 5,
    paddingBottom: 5,
    paddingHorizontal: 5,
    backgroundColor: theme.background,
    //borderBottomWidth: 1,
    borderColor: theme.border,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
    paddingHorizontal: 15,
  },
  headerIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  iconSpacing: {
    marginLeft: 15,
  },
  logo: {
    fontSize: 24,
    fontWeight: 'bold',
    color: theme.primary,
    alignSelf: 'center',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 6,
    paddingTop: 5,
    paddingHorizontal: 20,
    backgroundColor: theme.background,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
  },
  sectionHeaderText: {
    fontSize: 19,
    fontWeight: 'bold',
    color: theme.text,
    letterSpacing: 0.2,
  },
  guestBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.banner,
    borderRadius: 12,
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 6,
    paddingVertical: 10,
    paddingHorizontal: 14,
    elevation: 1,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  guestBannerText: {
    color: theme.guestBannerText,
    fontSize: 14,
    fontWeight: '500',
    flexWrap: 'wrap',
  },
  guestBannerLink: {
    color: theme.primary,
    textDecorationLine: 'underline',
    fontWeight: 'bold',
  },
  locationContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginTop: 10,
    marginBottom: 8,
  },
  locationButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.card,
    borderWidth: 1,
    height: 32,
    borderColor: theme.border,
    paddingVertical: 5,
    paddingHorizontal: 8,
    borderRadius: 20,
    minWidth: 105,
    maxWidth: 160,
  },
  locationButtonText: {
    fontSize: 12,
    color: theme.text,
    fontWeight: 'bold',
    marginLeft: 4,
  },
  locationIcon: {
    marginRight: 2,
  },
  disabledButton: {
    opacity: 0.6,
  },
  bottomNav: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 10,
    backgroundColor: theme.background,
    borderTopWidth: 1,
    borderTopColor: theme.border,
  },
  topRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    marginVertical: 8,
    flexWrap: 'nowrap',
  },
  titleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  viewAllText: {
    color: theme.primary,
    fontSize: 14,
    fontWeight: '500',
  },
  loader: {
    marginTop: 20,
  },
  noData: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 200,
  },
  infoText: {
    fontSize: 12,
    color: theme.text,
    marginLeft: 12,
    marginTop: 4,
    marginBottom: 8,
  },
  arrow: {
    position: 'absolute',
    top: -6,
    left: '50%',
    marginLeft: -6,
    width: 0,
    height: 0,
    borderLeftWidth: 6,
    borderRightWidth: 6,
    borderBottomWidth: 6,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: theme.banner,
  },

  card: {
    width: CARD_WIDTH,
    height: 300,
    backgroundColor: theme.card,
    borderRadius: 10,
    marginTop: 5,
    marginBottom: 15,
    elevation: 5,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    alignSelf: 'center',
    overflow: 'hidden',
    marginHorizontal: 8,
  },
  cardImage: {
    width: '100%',
    aspectRatio: 16 / 9,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    resizeMode: 'cover',
  },
  cardContent: {
    padding: 12,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: theme.text,
    flex: 1,
    marginRight: 6,
  },
  cardDescription: {
    fontSize: 14,
    color: theme.text,
    marginTop: 3,
  },
  cardPrice: {
    fontSize: 14,
    fontWeight: 'bold',
    marginVertical: 4,
    color: theme.primary,
  },
  cardClick: {
    color: theme.text,
    fontSize: 14,
    fontWeight: '500',
    marginTop: 4,
  },
  saveButton: {
    padding: 2,
    alignSelf: 'flex-start',
  },
  fallbackBanner: {
    backgroundColor: '#fceabb',
    padding: 10,
    borderRadius: 10,
    marginHorizontal: 16,
    marginBottom: 8,
  },
  fallbackBannerText: {
    fontSize: 13,
    fontWeight: '500',
    textAlign: 'center',
    color: '#8a5500',
  },
  badgeContainer: {
    position: 'absolute',
    top: 10,
    left: 10,
    backgroundColor: '#fff',
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 12,
    zIndex: 10,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 3,
    elevation: 2,
  },
  badgeText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#333',
  },

  // HiddenGemCard Specific
  gemOverlayAbsolute: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
    zIndex: 10,
  },
  gemTitle: {
    fontSize: 26,
    color: 'white',
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center',
  },
  gemSubtitle: {
    fontSize: 16,
    color: 'white',
    marginBottom: 20,
    textAlign: 'center',
  },
  gemButton: {
    backgroundColor: '#ff7f50',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 30,
  },
  gemButtonText: {
    color: 'white',
    fontWeight: '600',
  },
filterButtonIconWrapper: {
    padding: 6,
    borderRadius: 12,
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
filterButtonActive: {
    backgroundColor: theme.primaryBackground || '#e0f0ff',
  },
filterBadge: {
    position: 'absolute',
    top: -5,
    right: -5,
    backgroundColor: theme.primary,
    borderRadius: 10,
    paddingHorizontal: 5,
    paddingVertical: 2,
    minWidth: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
filterBadgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
  },
});

export const loadingCardStyles = (theme) => StyleSheet.create({
  card: {
    width: CARD_WIDTH,
    height: 300,
    borderRadius: 10,
    backgroundColor: theme.card,
    marginTop: 5,
    marginBottom: 15,
    marginHorizontal: 8,
    elevation: 5,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    overflow: 'hidden',
    alignSelf: 'center',
    position: 'relative',
  },
  block: {
    aspectRatio: 16 / 9,
    backgroundColor: '#d6d6d6',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    overflow: 'hidden',
  },
  line: {
    width: '70%',
    height: 20,
    backgroundColor: '#d6d6d6',
    borderRadius: 10,
    marginTop: 20,
    marginLeft: 16,
    overflow: 'hidden',
  },
  lineShort: {
    width: '50%',
    height: 20,
    backgroundColor: '#d6d6d6',
    borderRadius: 10,
    marginTop: 10,
    marginLeft: 16,
    overflow: 'hidden',
  },
  shimmerOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  gradient: {
    ...StyleSheet.absoluteFillObject,
  },
  overlay: {
    position: 'absolute',
    top: 110,
    left: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  loadingText: {
    marginTop: 3,
    fontSize: 16,
    color: theme.text,
    fontWeight: '500',
    textAlign: 'center',
  },
});

export const limitReachedCardStyles = (theme) => StyleSheet.create({
  card: {
    width: CARD_WIDTH,
    height: 300,
    backgroundColor: theme.card,
    borderRadius: 10,
    marginTop: 5,
    marginBottom: 15,
    marginHorizontal: 8,
    elevation: 5,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    alignSelf: 'center',
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  inner: {
    padding: 20,
    alignItems: 'center',
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
    color: theme.text,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 16,
    color: theme.textSecondary,
    textAlign: 'center',
    marginBottom: 20,
  },
  actions: {
    flexDirection: 'row',
  },
  button: {
    backgroundColor: '#FF6B6B',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
  },
  buttonText: {
    color: '#FFF',
    fontWeight: '600',
  },
});