// ItineraryOverviewStyles.js - Dark mode compatible
import { StyleSheet } from 'react-native';

export const createItineraryOverviewStyles = (theme) => StyleSheet.create({
  profilecontainer: {
    flex: 1,
    backgroundColor: theme.background,
    paddingBottom: 40,
    paddingTop: 0,
  },
  headerWrapper: {
    marginTop: 15,
    alignItems: 'center',
    marginBottom: 5,
  },
  savedtitle: {
    fontSize: 22,
    fontWeight: 'bold',
    textAlign: 'center',
    marginTop: 0,
    marginBottom: 5,
    color: theme.text,
  },
  subtitle: {
    fontSize: 14,
    color: theme.text,
    marginTop: 4,
    marginBottom: 2,
    textAlign: 'center',
  },
  progressText: {
    fontSize: 13,
    color: theme.text,
    marginTop: 4,
    textAlign: 'center',
  },
  stepCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.card,
    borderRadius: 12,
    padding: 14,
    marginHorizontal: 16,
    marginBottom: 12,
    elevation: 3,
    shadowColor: theme.shadow || '#000',
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    minHeight: 80,
  },
  stepCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  stepNumber: {
    fontSize: 13,
    fontWeight: 'bold',
    color: theme.primary,
  },
  stepTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.text,
    marginBottom: 2,
  },
  stepSub: {
    fontSize: 13,
    color: theme.text,
    marginTop: 2,
    marginBottom: 2,
  },
  mapButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.primary,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    justifyContent: 'center',
    alignSelf: 'center',
    width: '65%',
    marginTop: 20,
  },
  mapButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    marginLeft: 8,
    fontSize: 15,
  },
  trashButton: {
    padding: 8,
    marginLeft: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  fab: {
    position: 'absolute',
    right: 24,
    bottom: 70,
    width: 56,
    height: 56,
    backgroundColor: theme.primary,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 6,
    zIndex: 10,
  },
  ctaButton: {
    backgroundColor: theme.primary,
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 8,
    marginTop: 20,
    alignItems: 'center',
    alignSelf: 'center',
    elevation: 2,
  },
  ctaButtonText: {
    color: theme.card,
    fontWeight: 'bold',
    fontSize: 16,
  },
  emptyStateContainer: {
    alignItems: 'center',
    marginTop: 50,
    paddingHorizontal: 20,
  },
  emptyText: {
    fontSize: 18,
    fontWeight: '600',
    color: theme.text,
    textAlign: 'center',
    marginBottom: 8,
  },
  emptySubText: {
    color: theme.text,
    textAlign: 'center',
    fontSize: 15,
    marginBottom: 10,
  },
  guestProfileContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 32,
  },
  guestProfileText: {
    color: theme.guestBannerText,
    fontSize: 16,
    fontWeight: '500',
    textAlign: 'center',
    marginVertical: 18,
  },
  guestProfileLink: {
    color: theme.primary,
    textDecorationLine: 'underline',
    fontWeight: 'bold',
  },
  signupButton: {
    backgroundColor: theme.primary,
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 8,
    marginTop: 10,
  },
  signupButtonText: {
    color: theme.card,
    fontWeight: 'bold',
    fontSize: 16,
  },
  bottomNavWrapper: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: theme.background,
    elevation: 10,
    shadowColor: theme.shadow || '#000',
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: -2 },
    shadowRadius: 4,
    alignItems: 'center',
    paddingBottom: 16,
    paddingTop: 12,
  },
});
