// SettingsScreenStyles.js
import { StyleSheet } from 'react-native';

export const createSettingsScreenStyles = (theme) =>
  StyleSheet.create({
    stickyHeader: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      zIndex: 10,
      backgroundColor: theme.background,
      paddingHorizontal: 20,
      paddingTop: 0,
      height: 60,
    },
    container: {
      flex: 1,
      backgroundColor: theme.background,
      paddingTop: 0,
      paddingHorizontal: 0,
    },
    headerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 18,
      marginBottom: 12,
    },
    backButton: {
      padding: 0,
      marginRight: 8,
    },
    profileTitle: {
      flex: 1,
      fontSize: 20,
      fontWeight: 'bold',
      color: theme.text,
      textAlign: 'center',
    },
    sectionCard: {
      backgroundColor: theme.card,
      borderRadius: 14,
      marginHorizontal: 16,
      marginTop: 18,
      marginBottom: 6,
      padding: 16,
      elevation: 2,
      shadowColor: theme.shadow,
      shadowOpacity: 0.06,
      shadowOffset: { width: 0, height: 2 },
      shadowRadius: 4,
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: 'bold',
      color: theme.text,
      marginBottom: 10,
    },
    settingRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 10,
      paddingVertical: 4,
    },
    settingLabelRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    settingLabel: {
      fontSize: 15,
      color: theme.text,
      fontWeight: '500',
      textAlign: 'left',
    },
    settingDescription: {
      fontSize: 12,
      color: theme.text,
      marginTop: 2,
      textAlign: 'left',
    },
    logoutButton: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'center',
      marginTop: 20,
      marginBottom: 0,
      paddingVertical: 12,
      paddingHorizontal: 32,
      borderRadius: 8,
      minWidth: 200,
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.setborder,
      backgroundColor: theme.setbutton,
      //elevation: 3,
      //shadowColor: theme.shadow,
      //shadowOpacity: 0.06,
      //shadowOffset: { width: 0, height: 2 },
      //shadowRadius: 4,
    },
    logoutButtonText: {
      color: theme.text,
      fontWeight: 'bold',
      fontSize: 15,
      textAlign: 'center',
      marginHorizontal: 8,
    },
    deleteButton: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'center',
      marginTop: 24,
      marginBottom: 24,
      paddingVertical: 12,
      paddingHorizontal: 32,
      borderRadius: 8,
      minWidth: 180,
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.setborder,
      backgroundColor: theme.setbutton,
      //elevation: 2,
      //shadowColor: theme.shadow,
      //shadowOpacity: 0.06,
      //shadowOffset: { width: 0, height: 2 },
      //shadowRadius: 4,
    },
    deleteButtonText: {
      color: theme.text,
      fontWeight: 'bold',
      fontSize: 15,
      textAlign: 'center',
      marginHorizontal: 8,
    },
  });
