// SubscriptionScreenStyles.js - theme compatible
import { StyleSheet } from 'react-native';

export const createSubscriptionScreenStyles = (theme) => StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 10,
    backgroundColor: theme.background,
  },
  title: {
    fontSize: 26,
    fontWeight: 'bold',
    color: theme.text,
    textAlign: 'center',
    marginTop: 32,
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.primary,
    marginBottom: 10,
    textAlign: 'center',
  },
  offerBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: theme.banner,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 4,
    marginTop: 12,
    marginBottom: 4,
  },
  offerBadgeText: {
    color: '#FF5733',
    fontWeight: 'bold',
    marginLeft: 6,
    fontSize: 14,
  },
  offerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: 8,
  },
  offerText: {
    color: '#FF5733',
    fontWeight: '600',
    fontSize: 15,
  },
  countdownText: {
    color: theme.text,
    fontWeight: 'bold',
  },
  featureCard: {
    backgroundColor: theme.card,
    borderRadius: 16,
    padding: 18,
    marginVertical: 16,
    marginHorizontal: 16,
    elevation: 3,
    shadowColor: theme.shadow || '#000',
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
  },
  featureRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 6,
  },
  featureText: {
    marginLeft: 10,
    fontSize: 15,
    color: theme.text,
  },
  gradientButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    paddingVertical: 16,
    paddingHorizontal: 18,
    minHeight: 48,
  },
  upgradeButtonText: {
    color: '#222',
    fontWeight: 'bold',
    fontSize: 17,
    textAlign: 'center',
  },
  oneTimeButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 17,
    textAlign: 'center',
  },
  specialPriceText: {
    color: theme.text,
    fontSize: 15,
    textAlign: 'center',
    marginTop: 8,
    marginBottom: 12,
  },
  cancelButton: {
    alignSelf: 'center',
    marginTop: 18,
    marginBottom: 30,
  },
  cancelText: {
    color: theme.primary,
    fontWeight: 'bold',
    fontSize: 15,
    textAlign: 'center',
    textDecorationLine: 'underline',
  },
});
